title:  Hoofbeats
email:  holler@JakeMcClure.net
description: Understanding healthcare and technology in the Information Age
baseurl: ""
url: "http://JakeMcClure.net"

# ASSETS
logo:  "/assets/images/hoof-logo.svg"
logo-amp:  "/assets/images/hoofbeats-text.svg"
logo-quote: "/assets/images/hoofbeats-quote-text-container.svg"
logo-blog-text: "/assets/images/hoofbeats-text.svg"
author_image:  "/assets/images/author.png"

#PERSONNEL
name:  "Jake McClure, M.D."
author: jakemcclure
bio: Millennial physician, steward of practical integration of technology in healthcare and education
repository: jakemcclure/JakeMcClure.github.com

social:
  name: Jake McClure
  links:
    - https://twitter.com/Jake_McClure
    - https://medium.com/@JakeMcClure
    - https://nuzzel.com/Jake_McClure
    - https://www.highly.co/by/jakemcclure
    - https://www.facebook.com/
    - https://www.linkedin.com/in/JakeMcClure
    - https://github.com/jakemcclure

twitter:
  username: "@Jake_McClure"
twitter_username: Jake_McClure
youtube_username:  UC6yHs_AREfWOMhR3Qixf2aA
github_username:  JakeMcClure
snapchat_username: Jake-McClure

Twitter:
  username: Jake_McClure

google_analytics: UA-76343771-1
google_site_verification: UA-76343771-1
ga_username: UA-76343771-1

amazon:
  affiliates_tag: mcclure-20

# RECYCLED LINKS
prime-trial-banner: "amp/_store/_prime_trial_320x50.html"

# BUILD MODIFIERS
collections:
- graphics
- infographics
- apps
- workflows

# Gemfile, Gemfile.lock - The Gemfile and Gemfile.lock files are used by Bundler to keep track of the required gems and gem versions you need to build your Jekyll site.

excerpt_separator:  <!-- excerpt -->
paginate:  6
permalink:  pretty
show_drafts:  false
markdown:  kramdown
kramdown:
  parse_block_html:  true
  input:  GFM

sass:
  sass_dir:  _sass
  style:  compressed

exclude:
  - README.md
  - LICENSE
  - readme.md
  - bundle
  - src
  - CNAME
  - google*.html
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - script
  - scss
  - media
  - ".bundle"
  - vendor
  - node_modules

gems:
  - jekyll-feed
  - jekyll-admin
  - jekyll-paginate
  - jekyll-compose
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-livereload
  - jekyll-assets
  - autoprefixer-rails
  - neat
